### ISSUE TITLE
Inconsistencies in ffs branch

### ISSUE THREAD

**Issue by ghost** [SSAGESLabs/PySAGES#108]
There are some small issues with the recent commit [a6844c8](https://github.com/SSAGESLabs/PySAGES/commit/a6844c827558416c2b35a4063ef8dcc475518cda).

- `pysages/methods/__init__.py` is missing `from .ffs import FFS`
- `utils.py` from `main` branch is not merged with `utils.py` from `ffs` branch. The following function is missing: `try_import` and needs to be copied in.
- provided example for ffs has a bad initial configuration; choosing different atom ids solves the problem.

**Comment by pabloferz** [comment]
Thanks for the useful report @gosiazimon! We'll look into the issues.

**Comment by pabloferz** [comment]
We just rebased and exported `FFS`. In addition we changed the input so it should work now with the atom ids from the example. Hopefully this fixes all the issues.

**Comment by pabloferz** [comment]
We've removed the grid definition in the example to avoid any confusion (it was a leftover from copy-pasting). I'm closing this for now, but feel free to open further issues if have any other problem.
