### ISSUE TITLE
Spectral ABF failing test

### ISSUE THREAD

**Issue by InnocentBug** [SSAGESLabs/PySAGES#166]
In my PR #165 the spectral ABF test fails.
https://github.com/SSAGESLabs/PySAGES/runs/7439900314?check_suite_focus=true

I am pretty sure this is unrelated to the PR.

**Comment by pabloferz** [comment]
That's strange, it seem to come from `generate_context` when setting the positions. I will look closer into it.

**Comment by pabloferz** [comment]
Pinning the numpy version on the base Docker image seems to have fixed the issue. Closing this.
