### ISSUE TITLE
Not sure this is a bug

### ISSUE THREAD

**Issue by InnocentBug** [SSAGESLabs/PySAGES#168]
I think #163 changed how distance works if you don't use groups.

In my notebook, I used `Distance((0,1))` for the distance between particle 0 and particle 1.

That doesn't work now anymore.
It doesn't throw an error, and calculates something.

`Distance(([0], [1]))` seems to work though.

**Comment by pabloferz** [comment]
Does #169 fixes your issue?

**Comment by InnocentBug** [comment]
No it does not
