### ISSUE TITLE
Two files are almost the same.

### ISSUE THREAD

**Issue by InnocentBug** [SSAGESLabs/PySAGES#209]
`examples/openmm/metad/nacl/nacl.py`
and 
`examples/openmm/metad/nacl/nacl-displacement.py`
are almost the same file.

Can maybe one of them import stuff from the other one.
Maintance seems hard here.

**Comment by ricalessandri** [comment]
I agree, I was looking at them just yesterday. Maybe @sivadasetty can also suggest what to do here.
