### ISSUE TITLE
Error in the example of alanine dipeptide using colab

### ISSUE THREAD

**Issue by Chenghao-Wu** [SSAGESLabs/PySAGES#258]
I am trying to test the example of alanine dipeptide in colab but met the following error:

it happens when I tried to import pysages:

from pysages.grids import Grid
from pysages.colvars import DihedralAngle
from pysages.methods import Metadynamics

**import pysages**

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-13-93d8866a310a>](https://localhost:8080/#) in <module>
      2 from pysages.colvars import DihedralAngle
      3 from pysages.methods import Metadynamics
----> 4 import pysages

[/usr/local/lib/python3.9/dist-packages/pysages/__init__.py](https://localhost:8080/#) in <module>
     72 from .utils import dispatch  # noqa: E402, F401
     73 
---> 74 run = dispatch._functions["run"]
     75 analyze = dispatch._functions["analyze"]
     76 

AttributeError: 'Dispatcher' object has no attribute '_functions'

Thank you very much if any suggestion can be provided!

**Comment by pabloferz** [comment]
One of our dependencies got updates that break pysages. We are working on a more permanent fix, but for now you can add a cell (after the one where pysages is installed) with the following:

```
!pip install "plum-dispatch<2"
```

**Comment by Chenghao-Wu** [comment]
Thank you very much for the update. It works well this time!
