### ISSUE TITLE
Restart/Extending runs

### ISSUE THREAD

**Issue by cdeng485** [SSAGESLabs/PySAGES#264]
Is restart supported in pysages? I couldn't find any examples yet. If not, could you suggest some ways to work around that?

**Comment by pabloferz** [comment]
We have and implementation in #254. We haven't merged it yet, but you should be able to test it with:

```bash
pip install "git+https://github.com/SSAGESLabs/PySAGES.git@restarts"
```

**Comment by pabloferz** [comment]
Added in #254.
