### ISSUE TITLE
`pysages.utils.compat` fails to capture latest `plum` api changes

### ISSUE THREAD

**Issue by yzjin** [SSAGESLabs/PySAGES#278]
On line [78 and 79](https://github.com/SSAGESLabs/PySAGES/blob/3bd3f4c07d82b7a716085b11976094876a7fabfb/pysages/utils/compat.py#L78) of`pysages.utils.compat`, the function calls two functions in `plum`: `plum.get_origin()` and `plum.get_args()`. Both functions have been removed from `plum` in a recent [breaking change](https://github.com/beartype/plum/pull/94/commits/66072ddcd9825ab235e03d8ee2b3bb514e644335), and lead to `AttributeError`. These functions should probably be replaced by the native `typing.get_origin()` and `typing.get_args()`.

**Comment by pabloferz** [comment]
Solved by #280.
