### ISSUE TITLE
RMSD calculation may lead to NaN values

### ISSUE THREAD

**Issue by yzjin** [SSAGESLabs/PySAGES#305]
The RMSD collective variable [implementation](https://github.com/SSAGESLabs/PySAGES/blob/c0fe37ee2172502963b0a2c93047a86ad5d76247/pysages/colvars/orientation.py#L366) is problematic. It leads to numerical difference in the test case used [here](https://github.com/charnley/rmsd/blob/master/tests/test_kabsch.py) and NaN values even when the weights are removed [here](https://github.com/charnley/rmsd/blob/master/tests/test_kabsch_weighted.py). The root cause of such behavior is unknown yet and require further investigation.

**Comment by pabloferz** [comment]
The implementation now uses by default Kabsch algorithm as implemented in #321. Is this still happening or can we close the issue?

**Comment by yzjin** [comment]
I see! Closing this issue.

**Comment by pabloferz** [comment]
It's still may be worth making sure that it works against those test cases. Could you double check @yzjin?
