### ISSUE TITLE
`plum` version issues in midway3

### ISSUE THREAD

**Issue by yihengwuKP** [SSAGESLabs/PySAGES#316]
Hi, it seems that the default environment on midway3 stops working. I think it has to do with versions of `plum` and `typing_extensions`. Probably related to https://github.com/SSAGESLabs/PySAGES/issues/278. 

To reproduce this issue:
```bash
module unload pysages
module unload python
module load python/anaconda-2021.05
module load pysages 
conda activate pysages
cd examples/openmm/abf
python alanine-dipeptide_openmm.py
```
Traceback (most recent call last):
  File "alanine-dipeptide_openmm.py", line 7, in <module>
    import pysages
  File "/project/rcc/trung/PySAGES/pysages/__init__.py", line 62, in <module>
    from . import backends, colvars, methods  # noqa: E402, F401
  File "/project/rcc/trung/PySAGES/pysages/backends/__init__.py", line 4, in <module>
    from .core import (  # noqa: E402, F401
  File "/project/rcc/trung/PySAGES/pysages/backends/core.py", line 6, in <module>
    from pysages.typing import Any, Callable, JaxArray, NamedTuple, Optional
  File "/project/rcc/trung/PySAGES/pysages/typing.py", line 13, in <module>
    from pysages._compat import _jax_version_tuple, _plum_version_tuple
  File "/project/rcc/trung/PySAGES/pysages/_compat.py", line 8, in <module>
    from plum._version import __version_tuple__ as _plum_version_tuple
ImportError: cannot import name '__version_tuple__' from 'plum._version' (/software/python-anaconda-2021.05-el8-x86_64/envs/pysages/lib/python3.8/site-packages/plum/_version.py)    

Perhaps we should also consider changing the version requirements in [setup.cfg](https://github.com/SSAGESLabs/PySAGES/blob/main/setup.cfg).

For me personally I found that installing plum-dispatch=2.3.5 and typing_extensions=4.11.0 solves the issue.

**Comment by ndtrung81** [comment]
@yihengwuKP the `module load pysages` command is sufficient to load the necessary modules and set up the pysages env. Please try remove the lines
```
module load python/anaconda-2021.05
```
and
```
conda activate pysages
```
and rerun the job. WIth this change, I can run the alanine-dipeptide_openmm.py script without the issue.

**Comment by yihengwuKP** [comment]
Great! This solves the issues and I've update the hackmd: https://hackmd.io/Jbpc1E2kRbKPLUnmLKwINA?view#Installation-of-PySAGES-on-midway3

**Comment by ricalessandri** [comment]
Thanks @yihengwuKP ! Could you please actually do the same change in https://github.com/SSAGESLabs/PySAGES/wiki/PySAGES-installation-notes. We recently moved the hackmd.io to the Wiki. We should deprecate the hackmd document @pabloferz ? Maybe just add a BIG WARNING at the top of the hackmd that includes a link to the Wkki, before deleting the hackmd altogether?

**Comment by yihengwuKP** [comment]
Ah, I forgot about this! Thanks for pointing out the wiki

**Comment by yihengwuKP** [comment]
But it takes writing permissions for editing the wiki, right?

**Comment by ricalessandri** [comment]
🤔 perhaps... do you see any "edit" and "new page" buttons on the top-right of the page here: https://github.com/SSAGESLabs/PySAGES/wiki/PySAGES-installation-notes ?

**Comment by yihengwuKP** [comment]
it seems that I can't find it. Probably it's due to the editing permission: 
![image](https://github.com/SSAGESLabs/PySAGES/assets/39614623/461cbcd0-7fe4-491b-84d3-d80e3420241b)
[github wiki permissions](https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis)

**Comment by ricalessandri** [comment]
hi @pabloferz , could you give edit permission on the wiki to @yihengwuKP, if you're fine with that, of course?

**Comment by pabloferz** [comment]
I have sent an invite. After accepting @yihengwuKP, you should be able to edit the wiki. Thank you for looking into this!

**Comment by yihengwuKP** [comment]
Thanks Pablo! The wiki has been updated!
