### ISSUE TITLE
Plum dispatch>2.3.0 may cause compatibility issue with PySAGES

### ISSUE THREAD

**Issue by yzjin** [SSAGESLabs/PySAGES#323]
A [commit](https://github.com/beartype/plum/commit/8b43135ee0a93a8a3ffb08e75b14725b7e413562) in the plum dispatch 2.3.0 contains a change that is not well documented. The `Dispatcher.methods` [attribute](https://github.com/beartype/plum/blob/8b43135ee0a93a8a3ffb08e75b14725b7e413562/plum/resolver.py#L103) is no longer a list of `signature`, but become a list of `Method`, which pushed the signature to one level below and cause compatibility issues with pysages. The `has_method()` function [here](https://github.com/yzjin/PySAGES/blob/da514637b90165c27de8e0e9d1bd255969ebd679/pysages/utils/compat.py#L112) will no longer be able to fetch the signature of the method correctly. I will create a pull request later to address this issue.

**Comment by pabloferz** [comment]
Closed by #324
