### ISSUE TITLE
Memory allocation with multiple JAX/Simulation contexts

### ISSUE THREAD

**Issue by InnocentBug** [SSAGESLabs/PySAGES#82]
The preallocation of JAX causes issues when we run multiple JAX and/or simulation contexts.
We run into this situation as soon as we run multiple replica on a single GPU. (As for example with #68 )
The [documentation ](https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html) of JAX says to either set manual amounts for JAX, or disable the preallocation alltogether.

At the moment, I see disabling the preallocation as the only practical solution for us.
It might be a bit slower, but it should also prevent interference between GPU allocation of JAX and  the simulations.
We could set this behavior in the __init__.py of PySAGES, to avoid having users run into this issue.
Not the most elegant solution, but probably better than frustrated users.
What do you think @pabloferz

**Comment by pabloferz** [comment]
Yes, I do agree that this will be problematic. I wouldn't want to disable it by default when you are not generating different contexts. But JAX made it dependent on an environment variable, maybe we just have to override it during the module intialization unless the user has set already JAX's flags.

**Comment by InnocentBug** [comment]
Yes, that is what I meant. We can set the environment with initializing the module.
And we can respect user choices, by not overwriting.
But how should be detect if a user runs 1 or multiple contexts?

**Comment by pabloferz** [comment]
Unfortunately, as things are right now, we can't. So the only option is to disable by default as you said no matter what the user is doing (unless JAX's flags are already set).
